# Generated by Django 4.0.3 on 2022-03-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_uploadedfile_file_alter_uploadedfile_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='./files/'),
        ),
    ]
