# Generated by Django 4.0.3 on 2022-03-27 16:03

from django.db import migrations, models
import uploader.utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_id',
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(blank=True, null=True, storage=uploader.utils.storage.MinIO, upload_to='./uploader/files/'),
        ),
    ]
