# Generated by Django 4.0.3 on 2022-03-27 18:27

from django.db import migrations, models
import uploader.utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_remove_uploadedfile_file_id_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(blank=True, null=True, storage=uploader.utils.storage.MinIO, upload_to='.'),
        ),
    ]
